### ISSUE TITLE
Use compatibility range for dependencies versions

### ISSUE THREAD

**Issue by ncoden** [kmalakoff/node-nuget#7]
This packge use `*` for all dependencies:

```json
"dependencies": {
  "elementtree": "*",
  "event-stream": "*",
  "semver": "*",
  "shelljs": "*",
  "underscore": "*",
  "queue-async": "*",
  "vinyl-fs": "*"
}
```

This can break the package when a dependency make API changes. For example `vinyl` removed the `.pipe()` method from Vinyl objects, which this package use.

Please check your dependencies compatibility ranges and use them instead of `*`. The first step would be `"vinyl-fs": "~2"`.

**Comment by ncoden** [comment]
Poke @kmalakoff

**Comment by kmalakoff** [comment]
@ncoden I've updated vinyl-fs and republished. Thank you for reporting this.
